### ISSUE TITLE
Newlines at the end of the data cause it to report as invalid.

### ISSUE THREAD

**Issue by scottnelle** [alleyinteractive/simplechart#37]
If there's a newline at the end of your data it triggers a validation error. Trimming empty lines from the end of the input field before checking for validity will save a lot of confusion for people who are pasting in data.

**Comment by joshkadis** [comment]
@scottnelle I can't reproduce. Can you provide more info?

**Comment by joshkadis** [comment]
@scottnelle nvm, got it

**Comment by joshkadis** [comment]
thanks again
